"""
reports/generator.py — Structured threat intelligence report generator.
Produces analyst-ready reports from correlated intelligence data.
"""

import json
import logging
from datetime import datetime, timezone, timedelta
from typing import Any, Dict, List

from database.db import Database

logger = logging.getLogger("reports.generator")

REPORT_TEMPLATE = """# {title}

**Generated:** {generated_at}
**Platform:** CyberXTron Threat Intelligence Platform

---

## Executive Summary
{summary}

---

## Threat Actor
**Name:** {threat_actor}
**Confidence:** {confidence}

---

## Malware / Tools
{malware}

---

## Targeted Regions
{targeted_countries}

---

## Targeted Industries
{targeted_industries}

---

## Exploited CVEs
{cves}

---

## Impact Assessment
{impact}

---

## Indicators of Compromise (IOCs)

| Type | Value | Confidence | First Seen | Source |
|------|-------|------------|------------|--------|
{ioc_table}

---

## MITRE ATT&CK Techniques
{techniques}

---

## Recommendations
1. Block all listed IOCs at perimeter controls (firewall, proxy, EDR)
2. Hunt for listed IOCs across endpoint telemetry
3. Apply patches for listed CVEs immediately
4. Monitor for C2 beacon patterns associated with listed malware
5. Implement detection rules using listed MITRE techniques

---
*Report generated by CyberXTron TIP v1.0 | Classification: TLP:AMBER*
"""


class ReportGenerator:
    def __init__(self, db: Database):
        self.db = db

    async def generate_from_actor(self, threat_actor: str) -> Dict[str, Any]:
        iocs_data = await self.db.get_iocs(threat_actor=threat_actor, page_size=200)
        iocs = iocs_data.get("items", [])
        victims_data = await self.db.get_victims(group_name=threat_actor, page_size=50)
        victims = victims_data.get("items", [])
        countries = list({v.get("country", "") for v in victims if v.get("country")})
        industries = list({v.get("industry", "") for v in victims if v.get("industry")})
        malware_set = list({i.get("malware", "") for i in iocs if i.get("malware")})
        cves = [i["ioc"] for i in iocs if i.get("ioc_type") == "cve"]
        ioc_rows = [
            {
                "type": i.get("ioc_type", ""),
                "value": i.get("ioc", ""),
                "confidence": i.get("confidence_label", ""),
                "first_seen": i.get("first_seen", "")[:10],
                "sources": ", ".join(json.loads(i.get("sources", "[]"))),
            }
            for i in sorted(iocs, key=lambda x: x.get("confidence", 0), reverse=True)[:50]
        ]
        report = {
            "title": f"Threat Actor Report: {threat_actor}",
            "summary": (
                f"Intelligence report on '{threat_actor}' derived from "
                f"{len(iocs)} IOCs and {len(victims)} ransomware victim records."
            ),
            "threat_actor": threat_actor,
            "malware": ", ".join(malware_set),
            "targeted_countries": countries,
            "targeted_industries": industries,
            "cves": cves,
            "impact": self._impact(victims, iocs),
            "iocs": ioc_rows,
            "techniques": self._techniques(iocs, malware_set),
            "confidence": self._confidence(iocs),
        }
        report["raw_markdown"] = self._render(report)
        report["id"] = await self.db.save_report(report)
        return report

    async def generate_summary_report(self, days: int = 7) -> Dict[str, Any]:
        stats = await self.db.get_stats()
        date_from = (datetime.now(timezone.utc) - timedelta(days=days)).isoformat()
        iocs_data = await self.db.get_iocs(confidence="high", page_size=100, date_from=date_from)
        high_conf_iocs = iocs_data.get("items", [])
        victims_data = await self.db.get_victims(date_from=date_from, page_size=100)
        recent_victims = victims_data.get("items", [])
        top_groups = [g["group_name"] for g in stats.get("top_ransomware_groups", [])]
        top_actors = [a["threat_actor"] for a in stats.get("top_threat_actors", [])]
        countries = list({v.get("country", "") for v in recent_victims if v.get("country")})
        industries = list({v.get("industry", "") for v in recent_victims if v.get("industry")})
        ioc_rows = [
            {
                "type": i.get("ioc_type", ""),
                "value": i.get("ioc", ""),
                "confidence": i.get("confidence_label", ""),
                "first_seen": i.get("first_seen", "")[:10],
                "sources": ", ".join(json.loads(i.get("sources", "[]"))),
            }
            for i in high_conf_iocs[:30]
        ]
        report = {
            "title": "Weekly Threat Landscape Report",
            "summary": (
                f"Last {days} days: {stats.get('new_iocs_24h', 0)} new IOCs (24h), "
                f"{stats.get('new_victims_24h', 0)} new victims (24h). "
                f"Active groups: {', '.join(top_groups[:5])}."
            ),
            "threat_actor": ", ".join(top_actors[:5]) or "Multiple",
            "malware": "Ransomware, RATs, Infostealers, Botnets",
            "targeted_countries": countries[:10],
            "targeted_industries": industries[:10],
            "cves": [i["ioc"] for i in high_conf_iocs if i.get("ioc_type") == "cve"][:10],
            "impact": f"{len(recent_victims)} confirmed ransomware victims in period.",
            "iocs": ioc_rows,
            "techniques": [
                "T1566 - Phishing",
                "T1190 - Exploit Public-Facing Application",
                "T1486 - Data Encrypted for Impact",
                "T1041 - Exfiltration Over C2 Channel",
                "T1078 - Valid Accounts",
            ],
            "confidence": "high",
        }
        report["raw_markdown"] = self._render(report)
        report["id"] = await self.db.save_report(report)
        return report

    def _render(self, r: Dict) -> str:
        rows = "\n".join(
            f"| {x['type']} | `{x['value'][:60]}` | {x['confidence']} | {x['first_seen']} | {x['sources'][:40]} |"
            for x in r.get("iocs", [])
        )
        techs = "\n".join(f"- {t}" for t in r.get("techniques", [])) or "_None mapped_"
        return REPORT_TEMPLATE.format(
            title=r["title"],
            generated_at=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC"),
            summary=r.get("summary", ""),
            threat_actor=r.get("threat_actor", "Unknown"),
            confidence=r.get("confidence", "medium").capitalize(),
            malware=r.get("malware", "Unknown"),
            targeted_countries=", ".join(r.get("targeted_countries", [])) or "Unknown",
            targeted_industries=", ".join(r.get("targeted_industries", [])) or "Unknown",
            cves=", ".join(r.get("cves", [])) or "None identified",
            impact=r.get("impact", "Pending analysis"),
            ioc_table=rows or "_No IOCs_",
            techniques=techs,
        )

    def _impact(self, victims, iocs) -> str:
        parts = []
        if victims:
            parts.append(f"{len(victims)} confirmed victim organizations.")
        if iocs:
            high = sum(1 for i in iocs if i.get("confidence_label") == "high")
            parts.append(f"{high} high-confidence IOCs detected.")
        return " ".join(parts) or "Impact assessment pending further analysis."

    def _techniques(self, iocs, malware) -> List[str]:
        t = []
        types = {i.get("ioc_type") for i in iocs}
        ml = " ".join(malware).lower()
        if "url" in types: t.append("T1566.002 - Spearphishing Link")
        if "ip" in types: t.append("T1071.001 - Web Protocols (C2)")
        if "domain" in types: t.append("T1568 - Dynamic Resolution")
        if "cve" in types: t.append("T1190 - Exploit Public-Facing Application")
        if any(m in ml for m in ["ransomware", "lockbit", "blackcat", "conti"]):
            t.append("T1486 - Data Encrypted for Impact")
        if any(m in ml for m in ["stealer", "redline", "agent tesla"]):
            t.append("T1555 - Credentials from Password Stores")
        if any(m in ml for m in ["emotet", "qakbot", "icedid"]):
            t.append("T1055 - Process Injection")
        return list(dict.fromkeys(t))

    def _confidence(self, iocs) -> str:
        if not iocs: return "low"
        high = sum(1 for i in iocs if i.get("confidence_label") == "high")
        return "high" if high / len(iocs) > 0.5 else "medium"
